services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-16-alpine}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}

  # postgres-test:
  #   image: "postgres:${POSTGRES_VERSION:-16-alpine}"
  #   tmpfs:
  #     - /pgtmpfs
  #   ports:
  #     - "${POSTGRES_TEST_PORT:-5433}:5432"
  #   environment:
  #     POSTGRES_USER: "${POSTGRES_USER:-admin}"
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
  #     PGDATA: /pgtmpfs

  #api:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile

volumes:
  postgres-data:

